<?php

return array(
    "user_login" => "Логин",
    "register_now" => "Зарегистрироваться",
    "register_an_account" => "Зарегистрировать аккаунт",
    "user_login_meta_description" => "Войдите в ваш YTS аккаунт и начните скачивать фильмы YIFY с малым размером",
    "user_register_meta_description" => "Регистрация YTS аккаунта занимает считанные секунды и предоставляет полный доступ ко всему функционалу сайта.",
    "username_or_email" => "Имя пользователя или email",
    "username" => "Имя пользователя",
    "password" => "Пароль",
    "new_password" => "Новый пароль",
    "confirm_password" => "Подтверждение пароля",
    "confirm_new_password" => "Подтверждение пароля",
    "create_an_account" => "Создать аккаунт",
    "account_disabled" => "Аккаунт отключен",
    "account_banned" => "Аккаунт заблокирован",
    "you_are_banned" => "Вы заблокированы",
    "banned_mistake" => "Если вы думаете это ошибка, свяжитесь с нами: admin@yts.re",
    "incorrect_username_or_password" => "Неправильное имя пользователя или пароль",
    "registered_successfully" => "Вы зарегистрированы",
    "logged_in_successfully" => "Вы вошли",
    "logged_out_successfully" => "Вы вышли",
    "forgot_your_password" => "Забыли пароль?",
    "forgot_password" => "Забыли пароль?",
    "back_to_login" => "Назад к форме входа",
    "reset_password" => "Сбросить пароль",
    "password_reset_description" => "Если вы забыли пароль, просто введите ваш emal и мы отправим вам ссылку для сброса пароля.",
    "password_reset" => "Сброс пароля",
    "reset_your_password" => "Сбросить пароль",
    "password_reset_sent" => "Email для сброса пароля отправлено",
    "click_to_create_new_password" => "Пожалуйста нажмите эту кнопку для создания нового пароля для вашего аккаунта",
    "reset_code" => "Код для сброса пароля",
    "create_a_new_password" => "Создать новый пароль",
    "you_request_password_reset" => "Кажется, вы запросили сброс пароля.",
    "new_password_saved" => "Новый пароль сохранен",
    "commet_privileges_disabled" => "Комментирование отключено",
    "account_does_not_have_privileges" => "У вашего аккаунта нет привилегий",
);
