<?php

return array(
    "optional" => "необязательно",
    "loading_please_wait" => "Загрузка, пожалуйста подождите",
    "kind_regards" => "С уважением",
    "yts_team" => "Команда YTS",
    "hello" => "Привет",
    "save" => "Сохранить",
    "submit" => "Отправить",
    "generate" => "Сгенерировать",
    "statistics" => "Статистика",
    "edit" => "Редактировать",
    "downloads" => "Загрузки",
    "id" => "ID №",
    "title" => "Название",
    "text" => "Текст",
    "visible" => "Видимый",
    "new" => "Новый",
    "read_more" => "Подробнее",
    "date_added" => "Дата добавления",
    "delete" => "Удалить",
    "unknown" => "Неизвестный",
    "system_error" => "Системная ошибка (Error :code)",
    "please_try_again_later" => "Попытайтесь позже",
    "unauthorized" => "Недоступно (Error :code)",
    "you_cant_be_here" => "Вы не можете быть здесь",
    "description" => "Описание",
    "example" => "Пример",
    "examples" => "Примеры",
    "required" => "Обязательно",
    "default" => "По умолчанию",
    "type" => "Тип",
    "url" => "URL",
    "no_javascript_support" => "Javascript не поддерживается вашим браузером, пожалуйста включите Javascript чтобы пользоваться сайтом",
    "query_successful" => "Запрос успешен",
    "ignore" => "Игнорировать",
);
