<?php

return array(
    "search" => "Найти",
    "search_for_movie" => "Поиск фильмов&hellip;",
    "quick_search" => "Быстрый поиск",
    "quality" => "Качество",
    "genre" => "Жанр",
    "rating" => "Рейтинг",
    "order_by" => "Сортировать по",
    "search_term" => "Поисковый запрос",
    "keyword" => "Ключевое слово",
    
    "all" => "Все",
    
    "latest" => "Новые",
    "oldest" => "Старые",
    "seeds" => "Кол-во сидов",
    "peers" => "Кол-во пиров",
    "size" => "Размер",
    "year" => "Год",
    "rating" => "Рейтинг",
    "likes" => "Понравилось",
    "alphabetical" => "По алфавиту",
    "downloads" => "По загрузкам",
    
    "action" => "Экшн",
    "adventure" => "Приключения",
    "animation" => "Анимация",
    "biography" => "Биография",
    "comedy" => "Комедия",
    "crime" => "Преступления",
    "documentary" => "Документальный",
    "drama" => "Драма",
    "family" => "Семейный",
    "fantasy" => "Фэнтези",
    "film-noir" => "Фильм нуар",
    "history" => "Исторический",
    "horror" => "Ужасы",
    "music" => "Музыка",
    "musical" => "Мьюзикл",
    "mystery" => "Детектив",
    "news" => "Новости",
    "romance" => "Романтический",
    "sci-fi" => "Научная фантастика",
    "short" => "Короткометражный",
    "sport" => "Спортивный",
    "thriller" => "Триллер",
    "war" => "Военный",
    "western" => "Вестерн",
    
    
);
