<?php

return array(
    "search" => "Найти",
    "search_for_movie" => "Поиск фильма&hellip;",
    "quick_search" => "Быстрый поиск",
    "quality" => "Качество",
    "genre" => "Жанр",
    "rating" => "Рейтинг",
    "order_by" => "Сортировать по",
    "search_term" => "Поисковый запрос",
    "keyword" => "Ключевые слова",
    
    "all" => "Все",
    
    "latest" => "Сначала новые",
    "oldest" => "Сначала старые",
    "seeds" => "Количеству сидов",
    "peers" => "Количеству пиров",
    "size" => "Размеру",
    "year" => "Году",
    "rating" => "Рейтингу",
    "likes" => "Понравилось",
    "alphabetical" => "Алфавиту",
    "downloads" => "Скачиваниям",
    
    "action" => "Боевик",
    "adventure" => "Приключения",
    "animation" => "Мультфильм",
    "biography" => "Биография",
    "comedy" => "Комедия",
    "crime" => "Криминал",
    "documentary" => "Документальный",
    "drama" => "Драма",
    "family" => "Семейный",
    "fantasy" => "Фэнтези",
    "film-noir" => "Фильм-нуар",
    "history" => "История",
    "horror" => "Ужасы",
    "music" => "Музыка",
    "musical" => "Мьюзикл",
    "mystery" => "Детектив",
    "news" => "Новости",
    "romance" => "Мелодрама",
    "sci-fi" => "Фантастика",
    "short" => "Короткометражный",
    "sport" => "Спорт",
    "thriller" => "Триллер",
    "war" => "Военный",
    "western" => "Вестерн",
    
    
);
