<?php

return array(
    "not_found" => "Пользователь не найден",
    "no_users_found" => "Не найдено ни одного пользователя",
    "profile_disabled" => "Аккаунт отключен",
    "user_or_admin_disabled_profile" => "Или пользователь или администратор отключил аккаунт",
    "about" => "Информация о",
    "about_user" => "Информация о :username",
    "recent_downloads" => "Последние скачивания",
    "edit_user" => "Редактировать пользователя: :username",
    "edit_settings" => "Редактировать настройки",
    "change_password" => "Поменять пароль",
    "about_you" => "О вас",
    "about_text" => "Текст о вас",
    "avatar" => "Аватар",
    "upload_avatar" => "Загрузить аватар",
    "avatar_upload_warning" => "Использование любого порнографического или расистского материала приведет к блокировке аккаунта",
    "settings_have_been_saved" => "Настройки сохранены",
    "user_class" => "Тип пользователя",
    "last_seen" => "Последний вход",
    "joined" => "Зарегистрирован",
    "user_id" => "ID пользователя",
    "users" => "Пользователи",
    "user_actions" => "Действия пользователя",
    "enabled" => "Включен",
    "banned" => "Заблокирован",
    "disabled" => "Отключен",
    "comments_disabled" => "Комментирование отключены",
    "profile_disabled" => "Аккаунт отключен",
    "profile_hidden" => "Аккаунт скрыт",
    "user" => "Пользователь",
    "vip" => "VIP",
    "moderator" => "Модератор",
    "uploader" => "Загружатель",
    "developer" => "Разработчик",
    "supermoderator" => "Супер модератор",
    "administrator" => "Администратор",
    "profile_disabled_explanation" => "Это означает что никто не увидит ваш профиль",
    "use_magnets" => "Magnet ссылки",
    "use_magnets_explanation" => "Выбрать magnet ссылки для загрузок по умолчанию",
);
